### ISSUE TITLE
Multi homed server

### ISSUE THREAD

**Issue by riemers** [basschipper/homeassistant-doorbird-proxy#3]
I don't know why, but my Nas has 2 ips. For some reason it changed from using my main to my seconday ip  in the docker container and from that point on it would always get a 401 on Hass, always wrong password (even though the calls are still the same) disabled the second ip on the NAS and now all seems fine again. Really weird issue but maybe it rings a bell, if not you can close it, but was worth a mention.

**Comment by basschipper** [comment]
Did you run the proxy through Docker, or?

**Comment by riemers** [comment]
That was some time ago, forgot all about it. So i somehow managed to fixed it, can't recall it has been running smoothly now. Did see a doorbird component for Hass but that one isn't instant, but does polling instead (not so good) i use it to turn on the lights at the door for example too.. polling is too slow. So this one is still my favorite 👍

**Comment by basschipper** [comment]
I also tried the Home Assistant component, same issue. Only when holding the DoorBird button for a few seconds it's getting noticed by Home Assistant. But, seems like a solutions is on it's way: home-assistant/home-assistant/pull/11193
