### ISSUE TITLE
Transmit and Receive audio to and from DoorBird using DoorBird API

### ISSUE THREAD

**Issue by skarlekar** [basschipper/homeassistant-doorbird-proxy#4]
Hello,

While troubleshooting sending and receiving audio to the DoorBird using the DoorBird API, I came across your Git. I am wondering if you had success sending and receiving audio? I am having trouble sending/receiving the audio through the API. If you had success, I would love to hear from you.

Thanks,
Srini

**Comment by TadeasFrycak** [comment]
Have you solved this issue? I have a same problem and I do not know, how can I send some voice to the Doorbird.
Thank you

**Comment by basschipper** [comment]
No, I have no idea how to solve that. Also, I don't own a DoorBird anymore.
